esphome:
  name: server-fan-controller
  friendly_name: server_fan_controller

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "hlK27f/fEfucRplRc/VRN0i/NDzMw4S9OY9qPL79p0k="

ota:
  - platform: esphome
    password: "2afb8fc3494a9c6492fd16b0863025bf"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Server-Fan-Controller"
    password: "tn6q768pf4iZ"

captive_portal:

i2c:
  sda: 5
  scl: 6

emc2101:
  pwm:
    resolution: 8

output:
  - platform: emc2101
    id: fan_duty_cycle

sensor:
  - platform: emc2101
    internal_temperature:
      id: internal_temperature_sensor
      name: "Internal Temperature Sensor"
      on_value_range:
        - above: 40.0
          then:
            - fan.turn_on:
                id: server_fan
                speed: 60
            
        - below: 40.0
          then:
            - fan.turn_on:
                id: server_fan
                speed: 33
    speed:
      id: speed_sensor
      name: "Speed Sensor"
    duty_cycle:
      id: duty_cycle_sensor
      name: "Duty Cycle Sensor"
    update_interval: 5s
    

fan:
  - platform: speed
    output: fan_duty_cycle
    name: "Server Fan"
    id: server_fan
